MONGODB_HOST: mongodb-{{ env }}.yuvarajreddy.fun # mongodb-dev.daws86s.fun
REDIS_HOST: redis-{{ env }}.yuvarajreddy.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.yuvarajreddy.fun
CART_HOST: cart.backend-alb-{{ env }}.yuvarajreddy.fun
USER_HOST: user.backend-alb-{{ env }}.yuvarajreddy.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.yuvarajreddy.fun
MYSQL_HOST: mysql-{{ env }}.yuvarajreddy.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.yuvarajreddy.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.yuvarajreddy.fun